# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='prefix',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Mrs', 'Mrs.'), ('Mr.', 'Mr'), ('Dr.', 'Dr.')], default=('Ms.', 'Ms.'), max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_year',
            field=models.CharField(choices=[('PK', 'Preschool'), ('K', 'Kindergarten'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default=('PK', 'Preschool'), max_length=10),
        ),
    ]
